AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
